### ISSUE TITLE
megahit permission error in WSL miniconda environment

### ISSUE THREAD

**Issue by nahid18** [voutcn/megahit#286]
I have installed megahit into my WSL miniconda environment by this command:
`conda install -c bioconda megahit`
After installation, running `megahit -v`, `megahit --help` or `megahit --test` works perfectly.

However, whenever I try to run megahit for my dataset by running:
`megahit -1 "A1.fastq.gz" -2 "A2.fastq.gz" -o "result/A" --out-prefix "A"`
it throws the error below:

```
Traceback (most recent call last):
  File "/home/nahid/miniconda3/envs/xassembly/bin/megahit", line 1038, in <module>
    main()
  File "/home/nahid/miniconda3/envs/xassembly/bin/megahit", line 988, in main
    build_library()
  File "/home/nahid/miniconda3/envs/xassembly/bin/megahit", line 264, in checked_or_call
    func(*args, **kwargs)
  File "/home/nahid/miniconda3/envs/xassembly/bin/megahit", line 723, in build_library
    create_fifo('pe1', i, inpipe_cmd(opt.pe1[i]))
  File "/home/nahid/miniconda3/envs/xassembly/bin/megahit", line 710, in create_fifo
    os.mkfifo(fifo_path)
PermissionError: [Errno 1] Operation not permitted
```

How can I fix this issue? Please kindly help.

**Comment by nahid18** [comment]
Turns out I was using `.gz` files lol. I had to use the `.fastq` format file. 
And the program is working now.
