### ISSUE TITLE
Megahit not running on compressed files (gz)

### ISSUE THREAD

**Issue by martin-hartmann** [voutcn/megahit#303]
Hi,

I am trying to run megahit on a linux server using gz-compressed files, but it gives me the error message below.
It runs fine on unpacked files and it runs fine on compressed files locally on my MacBook.
Any idea what might be worng?

Thanks a lot,
Martin

2021-04-19 17:21:37 - MEGAHIT v1.2.9
2021-04-19 17:21:37 - Using megahit_core with POPCNT and BMI2 support
Traceback (most recent call last):
  File "/usr/local/bin/megahit", line 1038, in <module>
    main()
  File "/usr/local/bin/megahit", line 988, in main
    build_library()
  File "/usr/local/bin/megahit", line 264, in checked_or_call
    func(*args, **kwargs)
  File "/usr/local/bin/megahit", line 723, in build_library
    create_fifo('pe1', i, inpipe_cmd(opt.pe1[i]))
  File "/usr/local/bin/megahit", line 710, in create_fifo
    os.mkfifo(fifo_path)
PermissionError: [Errno 1] Operation not permitted

**Comment by rcmueller** [comment]
Dear Martin,

The permission problem while creating a named pipe (`mkfifo`) to extract compressed reads seems to be related to the mounted remote file system (cifs).
Without digging any deeper: Providing a local tmp dir (e.g., `--tmp-dir /tmp`) is working.

Cheers,
Ralf
