### ISSUE TITLE
OSError: [Errno 22] Invalid argument

### ISSUE THREAD

**Issue by vasudhajain29** [voutcn/megahit#319]
Hi

I am trying to run:

```
 megahit -1 R1.fastq.gz -2 R2.fastq.gz -o Megahit_out -t 80

```

and facing the following error:
2021-11-27 11:50:57 - MEGAHIT v1.2.9
2021-11-27 11:50:57 - Maximum number of available CPU thread is 8.
2021-11-27 11:50:57 - Number of thread is reset to the 8.
2021-11-27 11:50:58 - Using megahit_core with POPCNT support
Traceback (most recent call last):
  File "/Users/Admin1/opt/anaconda3/envs/megahit/bin/megahit", line 1038, in <module>
    main()
  File "/Users/Admin1/opt/anaconda3/envs/megahit/bin/megahit", line 988, in main
    build_library()
  File "/Users/Admin1/opt/anaconda3/envs/megahit/bin/megahit", line 264, in checked_or_call
    func(*args, **kwargs)
  File "/Users/Admin1/opt/anaconda3/envs/megahit/bin/megahit", line 723, in build_library
    create_fifo('pe1', i, inpipe_cmd(opt.pe1[i]))
  File "/Users/Admin1/opt/anaconda3/envs/megahit/bin/megahit", line 710, in create_fifo
    os.mkfifo(fifo_path)
OSError: [Errno 22] Invalid argument
```

i installed megahit using:

```
 conda install -c bioconda megahit
```

Please help.

**Comment by archanamadhav** [comment]
Hello, I'm facing the same issue. Any advice would be appreciated!

**Comment by qbdong122** [comment]
Hello, I'm facing the same issue. Any advice would be appreciated!

**Comment by mrxuzj** [comment]
Same error, have you solved this problem?
