### ISSUE TITLE
Running into a permission error while running a test data 

### ISSUE THREAD

**Issue by marynjerey** [voutcn/megahit#356]
(genome-assembly) [mchege@crcfe01 fastq]$ ~/.conda/envs/genome-assembly/bin/megahit -1 ERR2231568_1.fastqsanger.gz -2 ERR2231568_2.fastqsanger.gz -t 8 --k-min 21 --k-max 91 --k-step 12 -o megahit_result
2023-05-15 06:17:08 - MEGAHIT v1.2.9
2023-05-15 06:17:08 - Using megahit_core with POPCNT and BMI2 support
Traceback (most recent call last):
  File "/afs/crc.nd.edu/user/m/mchege/.conda/envs/genome-assembly/bin/megahit", line 1038, in <module>
    main()
  File "/afs/crc.nd.edu/user/m/mchege/.conda/envs/genome-assembly/bin/megahit", line 988, in main
    build_library()
  File "/afs/crc.nd.edu/user/m/mchege/.conda/envs/genome-assembly/bin/megahit", line 264, in checked_or_call
    func(*args, **kwargs)
  File "/afs/crc.nd.edu/user/m/mchege/.conda/envs/genome-assembly/bin/megahit", line 723, in build_library
    create_fifo('pe1', i, inpipe_cmd(opt.pe1[i]))
  File "/afs/crc.nd.edu/user/m/mchege/.conda/envs/genome-assembly/bin/megahit", line 710, in create_fifo
    os.mkfifo(fifo_path)
PermissionError: [Errno 1] Operation not permitted

**Comment by mrxuzj** [comment]
Same error. Have you solved this problem?
